version: '3.9'
services:
  db:
    image: mongo
    container_name: test-mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
  db-client:
    image: mongo-express
    restart: always
    ports:
      - 7085:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=secret
      - ME_CONFIG_MONGODB_URL=mongodb://root:secret@db:27017/
    depends_on:
      - db
  go-gin:
      build:
          context: .
          dockerfile: Dockerfile
      ports:
          - "8080:8080"
      restart: unless-stopped
      expose:
          - 8080

    
