version: '3.9'
services:
  mongo:
    image: mongo
    container_name: test-mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
  mongo-client:
    image: mongo-express
    restart: always
    ports:
      - 7085:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=secret
      - ME_CONFIG_MONGODB_URL=mongodb://root:secret@mongo:27017/
    depends_on:
      - mongo
  mysql-db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3316:3306'
    expose:
      - '3316'
  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: mysql-db
    depends_on:
      - mysql-db
    ports:
      - 8180:8080
  go-gin:
      build:
          context: .
          dockerfile: Dockerfile
      ports:
          - "8080:8080"
      restart: always
      depends_on:
        - mongo
        - mysql-db
      expose:
          - 8080
      volumes:
        - .:/app
    
