POST http://localhost:8091/users
Content-Type: application/json

{
    "name" : "new User",
    "email" : "new-email_d0@email.com",
    "address" : "testAddress",
    "phone_number" : "121232fe3113",
    "Password" : "password",
    "Details" : {
        "FirstName" : "new",
        "LastName" : "test"
    }
}